Repository skychatorg/skychat, pull requests merged in 2020-11, with the labels that each got.

#83 Various improvements
  app/client/css/abstract/util.scss
  app/client/css/styles.scss
  app/client/src/components/ConnectedUser.vue
  app/client/src/components/Message.vue
  app/client/src/components/PageContent.vue
  app/client/src/components/PageHeader.vue
  app/client/src/components/PlayerPreview.vue
  app/client/src/components/QuickActions.vue
  app/server/skychat/Session.ts
  app/server/skychat/SkyChat.ts
  app/server/skychat/UserController.ts
  app/server/skychat/commands/Command.ts
  app/server/skychat/commands/impl/core/AccountPlugin.ts
  app/server/skychat/commands/impl/core/ConnectedListPlugin.ts
  app/server/skychat/commands/impl/customization/ShopPlugin.ts
  app/server/skychat/commands/impl/moderation/IpPlugin.ts
  app/server/skychat/commands/impl/moderation/TrackerPlugin.ts
Labels: enhancement

#87 Fix responsiveness when using Safari/525.20.1+
  app/client/src/components/Message.vue
Labels: good first issue, help wanted

#88 Prevent loading stickers when the json list is empty in MessageHistory
  app/server/skychat/commands/impl/core/MessageHistoryPlugin.ts
Labels: good first issue
