Repository skychatorg/skychat, pull requests merged in 2021-04, with the labels that each got.

#98 Implement rooms & Fix log fuzzer & Make fake history stickers deterministic & Improve docker support
  Dockerfile
  README.md
  app/client/css/styles.scss
  app/client/src/components/ConnectedList.vue
  app/client/src/components/MessageForm.vue
  app/client/src/components/MessagesOverlay.vue
  app/client/src/components/MiddleColumn.vue
  app/client/src/components/PageContent.vue
  app/client/src/components/RoomList.vue
  app/client/src/components/UserPreview.vue
  app/client/src/skychat/SkyChatClient.js
  app/client/src/store/store.js
  app/server/skychat/Config.ts
  app/server/skychat/Message.ts
  app/server/skychat/MessageController.ts
  app/server/skychat/Room.ts
  app/server/skychat/Session.ts
  app/server/skychat/SkyChat.ts
  app/server/skychat/UserController.ts
  app/server/skychat/commands/impl/core/AccountPlugin.ts
  app/server/skychat/commands/impl/core/GiveMoneyPlugin.ts
  app/server/skychat/commands/impl/core/HelpCommand.ts
  app/server/skychat/commands/impl/core/MailPlugin.ts
  app/server/skychat/commands/impl/core/MessageCommand.ts
  app/server/skychat/commands/impl/core/MessageHistoryPlugin.ts
  app/server/skychat/commands/impl/core/RankPlugin.ts
  app/server/skychat/commands/impl/customization/CursorPlugin.ts
  app/server/skychat/commands/impl/customization/ShopPlugin.ts
  app/server/skychat/commands/impl/entertainment/GuessTheNumberPlugin.ts
  app/server/skychat/commands/impl/moderation/BanPlugin.ts
  app/server/skychat/commands/impl/moderation/IpPlugin.ts
  app/server/skychat/commands/impl/moderation/OfferMoneyPlugin.ts
  app/server/skychat/commands/impl/moderation/TrackerPlugin.ts
  app/server/skychat/commands/impl/optional/LogFuzzerPlugin.ts
  app/server/skychat/commands/impl/optional/ReminderPlugin.ts
  app/server/skychat/commands/impl/youtube/YoutubePlugin.ts
  config/preferences.json.template
  docker-compose.yml
  package.json
  scripts/docker-start.sh
Labels: enhancement, invalid, security

#101 Major frontend refactoring & Minor fixes
  Dockerfile
  app/client/src/SkyChatClient.js
  app/client/src/components/PlayerBackground.vue
  app/client/src/index.js
  app/client/src/store.js
  app/client/src/vue/AppHeader.vue
  app/client/src/vue/SkychatApp.vue
  app/client/src/vue/components/form/MessageForm.vue
  app/client/src/vue/components/form/QuickActions.vue
  app/client/src/vue/components/form/TypingList.vue
  app/client/src/vue/components/layout/TchatMiddleColumn.vue
  app/client/src/vue/components/message/MessageList.vue
  app/client/src/vue/components/message/SingleMessage.vue
  app/client/src/vue/components/modal/YoutubeVideoSearcher.vue
  app/client/src/vue/components/overlay/CinemaModeOverlay.vue
  app/client/src/vue/components/overlay/CursorOverlay.vue
  app/client/src/vue/components/poll/PollList.vue
  app/client/src/vue/components/room/RoomList.vue
  app/client/src/vue/components/user/UserList.vue
  app/client/src/vue/components/user/UserListRow.vue
  app/client/src/vue/components/user/UserPreview.vue
  app/client/src/vue/components/video-player/VideoPlayer.vue
  app/client/src/vue/components/video-player/VideoPlayerPreview.vue
  app/client/src/vue/pages/AuthPage.vue
  app/client/src/vue/pages/TchatPage.vue
  app/server/skychat/MessageFormatter.ts
  app/server/skychat/Room.ts
  app/server/skychat/plugins/core/MessageHistoryPlugin.ts
  app/server/skychat/plugins/customization/CursorPlugin.ts
  app/server/skychat/plugins/entertainment/DailyRoll.ts
  docker-compose.yml
  scripts/docker-start.sh
Labels: QA, bug, enhancement, invalid

#102 Implement Stats plugin
  app/server/skychat/plugins/entertainment/StatsPlugin.ts
  config/preferences.json.template
Labels: enhancement
